version: '3'
services:
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:${DB_PORT}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./wp-content:/var/www/html/wp-content
    deploy:
      replicas: ${REPLICAS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${DOMAIN}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.${DOMAIN}.loadbalancer.server.port=80"
