version: '3'
services:
  wordpress:
    image: wordpress:latest
    container_name: wp-${HOSTNAME}
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:${DB_PORT}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    deploy:
      replicas: ${REPLICAS}
      update_config:
        parallelism: 1
    labels:
      - "traefik.http.routers.${DOMAIN}.rule=Host(`${DOMAIN}`)"
